default:  fxctmp9_tmp\vertexlit_and_unlit_generic_treesway_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_treesway_vs30.vcs

fxctmp9_tmp\vertexlit_and_unlit_generic_treesway_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_treesway_vs30.vcs: vertexlit_and_unlit_generic_treesway_vs20.fxc common_hlsl_cpp_consts.h common_pragmas.h common_vs_fxc.h common_fxc.h tree_sway.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." vertexlit_and_unlit_generic_treesway_vs20.fxc-----vertexlit_and_unlit_generic_treesway_vs30
	echo vertexlit_and_unlit_generic_treesway_vs20.fxc>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo tree_sway.h>> filestocopy.txt

